title: Julian Velling
tagline: Web Design & Development
description: Hi! My name is Julian and I do web design and development!
url: "https://www.julianvelling.de"

lang: en
locale: en_GB

social:
  name: Julian Velling
  links:
    - https://github.com/juve33
email: kontakt@julianvelling.de

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

markdown: GFM

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"